### PR TITLE
helper/resource: Additional Go documentation for TestCheck and TestMatch functions

### LINKED ISSUE #885: testCheckResourceAttrSet() is broken for all but TypeString attributes
I recently spent about 12 hours trying to find a bug in my code which would result in the testing function `testCheckResourceAttrSet()` reporting a certain resource attribute was not set.

In fact, the attribute WAS set, and the function contains a bug; when you try to check an attribute which is not a simple `map[string]string` and instead, eg. `[]map[string]interface{}`, the function will fail.

The proposal here is to add a comment to the function so anyone using autocomplete in the future is aware this function should be used for string attributes only. 

To verify this is the case, I wrote a simple `panic()` test inside my resource code:
```go
if dashs, ok := d.GetOk("dashboards"); ok {
  panic(fmt.Errorf("dashboards attr = %#v", dashs))
}
```

this **guaranteed** the test would exist in a stack trace if the resource attribute `dashboards` was set; it did. Removing this small bit of code resulted in the test framework error:

```console
?       github.com/grafana/terraform-provider-grafana   [no test files]
=== RUN   TestAccDataSourceDashboardsAllAndByFolderID
    data_source_dashboards_test.go:38: Step 1/1 error: Check failed: Check 5/9 error: data.grafana_dashboards.all: Attribute 'dashboards' expected to be set
--- FAIL: TestAccDataSourceDashboardsAllAndByFolderID (3.46s)
```

### PR DESCRIPTION
**Pull request by bflad**
Closes #885

### CODE REVIEW

File: helper/resource/testing.go [hunk 1]
```diff
@@ -752,10 +755,47 @@ func ComposeAggregateTestCheckFunc(fs ...TestCheckFunc) TestCheckFunc {
...
+//
+// For data sources, the name parameter is a combination of the keyword "data",
+// a period (.), the data source type, a period (.), and the name label. The
+// name for the below example configuration would be
+// "data.myprovider_thing.example".
+//
+//     data "myprovider_thing" "example" { ... }
+//
+// The key parameter is an attribute path in Terraform CLI 0.11 and earlier
+// "flatmap" syntax. Keys start with the attribute name of a top-level
```
Comment (detro) [inline helper/resource/testing.go:788]: Does it make sense to make references to what is now an "ancient" version of Terraform? Do we have a public doc explaining this `"flatmap" syntax`?

File: helper/resource/testing.go [hunk 2]
```diff
@@ -789,8 +829,41 @@ func testCheckResourceAttrSet(is *terraform.InstanceState, name string, key stri
...
+// attribute. Use the following special key syntax to inspect list, map, and
+// set attributes:
+//
+// - .{NUMBER}: List value at index, e.g. .0 to inspect the first element. Use
+//              the TestCheckTypeSet* and TestMatchTypeSet* functions instead
+//              for sets.
+// - .{KEY}: Map value at key, e.g. .example to inspect the example key value
+// - .#: Number of elements in list or set
+// - .%: Number of elements in map
```
Comment (detro) [inline helper/resource/testing.go:859]: As above, an "end to end" example would put a nice bow here.

File: helper/resource/testing.go [hunk 3]
```diff
@@ -844,8 +917,36 @@ func testCheckResourceAttr(is *terraform.InstanceState, name string, key string,
...
+//
+//     data "myprovider_thing" "example" { ... }
+//
+// The key parameter is an attribute path in Terraform CLI 0.11 and earlier
+// "flatmap" syntax. Keys start with the attribute name of a top-level
+// attribute. Use the following special key syntax to inspect underlying
+// values of a list or map attribute:
+//
+// - .{NUMBER}: List value at index, e.g. .0 to inspect the first element
+// - .{KEY}: Map value at key, e.g. .example to inspect the example key value
```
Comment (detro) [inline helper/resource/testing.go:944]: About the example, as above.

File: helper/resource/testing.go [hunk 4]
```diff
@@ -892,8 +993,39 @@ func testCheckNoResourceAttr(is *terraform.InstanceState, name string, key strin
...
+// "flatmap" syntax. Keys start with the attribute name of a top-level
+// attribute. Use the following special key syntax to inspect list, map, and
+// set attributes:
+//
+// - .{NUMBER}: List value at index, e.g. .0 to inspect the first element. Use
+//              the TestCheckTypeSet* and TestMatchTypeSet* functions instead
+//              for sets.
+// - .{KEY}: Map value at key, e.g. .example to inspect the example key value
+// - .#: Number of elements in list or set
+// - .%: Number of elements in map
```
Comment (detro) [inline helper/resource/testing.go:1023]: ditto

File: helper/resource/testing.go [hunk 5]
```diff
@@ -949,8 +1084,38 @@ func TestCheckModuleResourceAttrPtr(mp []string, name string, key string, value
...
```
Comment (detro) [inline helper/resource/testing.go:1118]: ditto

**Review by detro — APPROVED** [review]
This is AWESOMELY USEFUL. I myself have learned more about those functions by reading this doc.

I left a couple of comments, but are nitpicks and it's ok if you don't feel like it.

File: helper/resource/testing.go (hunk 1 above)
Comment (bflad) [reply helper/resource/testing.go:788]: I would love to reference something, but I'm not sure if there's any terraform.io documentation left on it. 🙁  I'll do some digging, but I'm doubtful. In place of finding that, I'm wondering if [Go testable examples](https://go.dev/blog/examples) might help at least slightly here.

File: helper/resource/testing.go [hunk 6]
```diff
@@ -752,10 +755,47 @@ func ComposeAggregateTestCheckFunc(fs ...TestCheckFunc) TestCheckFunc {
...
+//
+//     data "myprovider_thing" "example" { ... }
+//
+// The key parameter is an attribute path in Terraform CLI 0.11 and earlier
+// "flatmap" syntax. Keys start with the attribute name of a top-level
+// attribute. Use the following special key syntax to inspect underlying
+// values of a list or map attribute:
+//
+// - .{NUMBER}: List value at index, e.g. .0 to inspect the first element
+// - .{KEY}: Map value at key, e.g. .example to inspect the example key value
```
[the remark this answers is not in the document]
Comment (bflad) [reply helper/resource/testing.go:793]: Yeah totally -- I meant to implement [Go testable examples](https://go.dev/blog/examples) for these as part of this update.

It's going to be a little awkward though, because its only recommended to implement these for Computed values, but I'll essentially have to show the configuration equivalent so it makes more sense looking at it.

File: helper/resource/testing.go (hunk 1 above)
Comment (bflad) [reply helper/resource/testing.go:788]: The closest thing I can find is: https://www.terraform.io/language/configuration-0-11/interpolation#attributes-of-other-resources, but I think linking to that would honestly be more confusing than anything. The flatmap bits were a detail of the previous state storage mechanism. I've uploaded some TestCheckFunc examples instead.

File: helper/resource/testing.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (bflad) [reply helper/resource/testing.go:793]: I've uploaded some TestCheckFunc examples.

File: helper/resource/testing.go (hunk 2 above)
Comment (bflad) [reply helper/resource/testing.go:859]: I've uploaded some TestCheckFunc examples.

File: helper/resource/testing.go (hunk 3 above)
Comment (bflad) [reply helper/resource/testing.go:944]: I've uploaded some TestCheckFunc examples.

File: helper/resource/testing.go (hunk 4 above)
Comment (bflad) [reply helper/resource/testing.go:1023]: I've uploaded some TestCheckFunc examples.

File: helper/resource/testing.go (hunk 5 above)
Comment (bflad) [reply helper/resource/testing.go:1118]: I've uploaded some TestCheckFunc examples.

File: helper/resource/testing.go [hunk 7]
```diff
@@ -752,10 +755,47 @@ func ComposeAggregateTestCheckFunc(fs ...TestCheckFunc) TestCheckFunc {
 	}
 }
 
-// TestCheckResourceAttrSet is a TestCheckFunc which ensures a value
-// exists in state for the given name/key combination. It is useful when
-// testing that computed values were set, when it is not possible to
-// know ahead of time what the values will be.
+// TestCheckResourceAttrSet ensures any value exists in the state for the
```
[the remark this answers is not in the document]
Comment (detro) [reply helper/resource/testing.go:758]: Of course. Naming, especially that lasts the test of time, is hard.

**Review by detro — APPROVED** [review]
The use of Go testable examples is a great solution, much better than keeping it in code.

In Rust there is something similar: the compiler can be told that part of the doc is an executable example and so it handles that in a similar fashion to here.

**Comment by detro** [comment]
Screenshot 2022-03-24 at 11 42 51
I was curious to see the test examples in action, so I ran `godoc` locally.

I think you might need to tweak the formatting a bit, as the godoc renderer is getting a bit confused in some points.

**Comment by detro** [comment]
But godoc formatting aside, this is excellent.
