### PR TITLE
fix meta.SDKPrerelease parsing

### LINKED ISSUE #444: Incorrect values for meta.SDKVersion and meta.SDKPrerelease
For the 2.0.0-rc.1 release, the `meta.SDKVersion` got set to `"2.0.0-rc.1"` and the `meta.SDKPrerelease` got set to `""`. This is due to a faulty regexp in our release scripts.

Fortunately, this should only impact users that are referencing `meta.SDKVersion` and `meta.SDKPrerelease` directly. Users using `meta.SDKVersionString()` will receive the correct result; it's just not split into its constituent variables correctly.

We should resolve this for 2.0.0-rc.2, but because the impact is fairly minimal for the moment--most users probably won't notice--it probably doesn't justify an emergency release.

### PR DESCRIPTION
**Pull request by kmoe**
fixes #444 

Consolidate regex for semver version into `semverRegex` variable, which captures the _version core_ (e.g. 1.2.3) and _version prerelease_ (e.g. rc.1) in two separate capture groups.

Write the appropriate values for `SDKVersion` and `SDKPrerelease` in `meta.go`. 

## Tests performed

Commits in this PR test the following behaviours in order:

#### https://github.com/hashicorp/terraform-plugin-sdk/pull/448/commits/ce9619d3908d0b2b8c72f075c574e304fdb0ec96: CHANGELOG.md contains release number with prerelease, `0.0.1-rc.1` 
 - `SDKVersion` is set to `"0.0.1"`
 - `SDKPrerelease` is set to `"rc.1"`
 - version number in commit (and tag, not shown) is set to `0.0.1-rc.1`

#### https://github.com/hashicorp/terraform-plugin-sdk/pull/448/commits/7fc7bdb17a0500efc3066a06277542d7932f4401: CHANGELOG.md contains release number without prerelease, `0.0.2`
 - `SDKVersion` is set to `"0.0.2"`
 - `SDKPrerelease` is set to `""`
 - version number in commit (and tag, not shown) is set to `0.0.2`

When this PR is approved, I will reset back to https://github.com/hashicorp/terraform-plugin-sdk/pull/448/commits/793ec14c19b3a389d7e95c47d89038103e7e6a7d to remove the test commits.

### CODE REVIEW

**Comment by appilon** [comment]
Porting to V1 is of low priority but I added the label for tracking

File: scripts/release/release.sh [hunk 1]
```diff
@@ -57,8 +71,8 @@ function changelogMain {
 }
 
 function modifyVersionFiles {
-  sed -i "s/var SDKVersion =.*/var SDKVersion = \"${TARGET_VERSION}\"/" meta/meta.go
-  sed -i "s/var SDKPrerelease =.*/var SDKPrerelease = \"\"/" meta/meta.go
+  sed -i "s/var SDKVersion =.*/var SDKVersion = \"${TARGET_VERSION_CORE}\"/" meta/meta.go
```
Comment (appilon) [inline scripts/release/release.sh:74]: I think this PR looks good, can you cleanup the changes done for testing and squash the commits?
