### PR TITLE
Remove TF_SCHEMA_PANIC_ON_ERR

### LINKED ISSUE #451: Enable TF_SCHEMA_PANIC_ON_ERROR Only During Acceptance Testing
### SDK version

```
v2.0.0-rc.1
```

### Use-cases

For a long time, the acceptance testing framework has accepted the `TF_SCHEMA_PANIC_ON_ERROR` environment variable as a way to tease out state setting and drift detection issues in resources where the `(*helper/schema.ResourceData).Set()` call is not error checked, e.g.

```go
func ExampleThingRead(d *schema.ResourceData, meta interface{}) error {
  // ...
  d.Set("attr", someInvalidValue)
  // ...
}
```

In the upcoming SDK v2, the value has been flipped on by default, which is great for catching provider bugs, but unfortunately at the potential expense of very poor user experience. When a resource panics, it makes the resource practically unusable (since this affects refresh) and potentially can leave the user's Terraform state in an errant state (depending on how Terraform CLI handles the panic). Considering that it can be fairly easy for larger providers to miss failing acceptance testing during merges and before releases, this can cause a lot of issues to be submitted and an immediate need to cut a bug fix release. Asking users to run with `TF_SCHEMA_PANIC_ON_ERROR` disabled could be problematic in its own right.

### Proposal

Consider guarding the `TF_SCHEMA_PANIC_ON_ERROR` behavior to only be enabled by default in the acceptance testing framework. For example, acceptance testing today requires `TF_ACC=1` for `helper/resource.Test()` / `helper/resource.ParallelTest()` so that could potentially be used.

### References

- https://github.com/hashicorp/terraform-plugin-sdk/pull/344

### PR DESCRIPTION
**Pull request by appilon**
Schema errors will panic if TF_ACC is set, panicking is no longer on by default
but cannot be opted out of when running acceptance tests. This does not address #455 .

Technically a breaking change `schema.PanicOnErr` is no longer an exported var

Closes #451

### CODE REVIEW

File: helper/resource/testing_test.go [hunk 1]
```diff
@@ -18,11 +18,6 @@ import (
 )
 
 func init() {
-	// TODO: Remove when we remove the guard on id checks
```
Comment (appilon) [inline helper/resource/testing_test.go:21]: This is not referenced anywhere else

File: helper/schema/schema_test.go [hunk 2]
```diff
@@ -8209,48 +8209,26 @@ func TestValidateAtLeastOneOfAttributes(t *testing.T) {
...
-	}
-
-	os.Setenv(PanicOnErr, oldEnv)
-}
-
-func Test_panicOnErrParsableFalse(t *testing.T) {
-	oldEnv := os.Getenv(PanicOnErr)
-
-	os.Setenv(PanicOnErr, "false")
+	os.Setenv("TF_ACC", "")
```
Comment (paultyng) [inline helper/schema/schema_test.go:8215]: oh god this is just asking for a race condition problem 😭

Comment (appilon) [reply helper/schema/schema_test.go:8215]: Agreed, these unit tests aren't super high value so we could ditch the tests if you find this too "anti pattern"

**Comment by appilon** [comment]
@paddycarver no problem will do.
