### PR TITLE
helper/resource/testing_new: update import state testing

### LINKED ISSUE #532: V2 ImportState Testing Ignoring ExpectError
### SDK version

```
v2.0.1
```

### Relevant provider source code

```go
func TestAccAWSKinesisFirehoseDeliveryStream_basic(t *testing.T) {
	resourceName := "aws_kinesis_firehose_delivery_stream.test"
	rInt := acctest.RandInt()

	funcName := fmt.Sprintf("aws_kinesis_firehose_ds_import_%d", rInt)
	policyName := fmt.Sprintf("tf_acc_policy_%d", rInt)
	roleName := fmt.Sprintf("tf_acc_role_%d", rInt)
	var stream firehose.DeliveryStreamDescription

	config := testAccFirehoseAWSLambdaConfigBasic(funcName, policyName, roleName) +
		fmt.Sprintf(testAccKinesisFirehoseDeliveryStreamConfig_extendedS3basic,
			rInt, rInt, rInt, rInt)

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:     func() { testAccPreCheck(t) },
		Providers:    testAccProviders,
		CheckDestroy: testAccCheckKinesisFirehoseDeliveryStreamDestroy,
		Steps: []resource.TestStep{
			{
				Config: config,
				Check: resource.ComposeTestCheckFunc(
					testAccCheckKinesisFirehoseDeliveryStreamExists(resourceName, &stream),
					testAccCheckAWSKinesisFirehoseDeliveryStreamAttributes(&stream, nil, nil, nil, nil, nil),
				),
			},
			{
				ResourceName:      resourceName,
				ImportState:       true,
				ImportStateVerify: true,
			},
			// Ensure we properly error on malformed import IDs
			{
				ResourceName:  resourceName,
				ImportState:   true,
				ImportStateId: "just-a-name",
				ExpectError:   regexp.MustCompile(`Expected ID in format`),
			},
			{
				ResourceName:  resourceName,
				ImportState:   true,
				ImportStateId: "arn:aws:firehose:us-east-1:123456789012:missing-slash",
				ExpectError:   regexp.MustCompile(`Expected ID in format`),
			},
		},
	})
}
```

### Terraform Configuration Files

Please see the Terraform AWS Provider repository, but presumably this would happen with any resource configuration and `ImportState` + `ExpectError` defined.

### Debug Output

Please ask if you need it.

### Expected Behavior

`ExpectError` passes when import error message matches regular expression, which was the behavior in SDK v1. Otherwise this change to be documented in the SDK v2 upgrade guide.

### Actual Behavior

```
=== CONT  TestAccAWSKinesisFirehoseDeliveryStream_basic
    TestAccAWSKinesisFirehoseDeliveryStream_basic: testing_new_import_state.go:74: failed to import: terraform failed: exit status 1

        stderr:

        Error: Expected ID in format of arn:PARTITION:firehose:REGION:ACCOUNTID:deliverystream/NAME and provided: just-a-name



--- FAIL: TestAccAWSKinesisFirehoseDeliveryStream_basic (101.43s)
```

### Steps to Reproduce

1. `TF_ACC=1 go test ./aws -v -count 1 -timeout 120m -parallel 20 -run='TestAccAWSKinesisFirehoseDeliveryStream_basic'`

### PR DESCRIPTION
**Pull request by anGie44**
Closes #532 

`testStepNewImportState` can now return the error (if any) of the underlying method that imports the resource, thus allowing for error handling w/in `runNewTest` when `step.ImportState` is set to `true`. Special error handling is needed here to account for provider acceptance tests that check for expected errors during `ImportState` test steps as illustrated in #532. 

Output of previously failing acceptance test:
```
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_basic (303.34s)
```

### CODE REVIEW

File: helper/resource/testing_new.go [hunk 1]
```diff
@@ -106,8 +106,17 @@ func runNewTest(t testing.T, c TestCase, helper *tftest.Helper) {
...
 		if step.ImportState {
 			err := testStepNewImportState(t, c, helper, wd, step, appliedCfg)
-			if err != nil {
-				t.Fatal(err)
+			if step.ExpectError != nil {
+				if err == nil {
+					t.Fatalf("Step %d/%d error running import: expected an error but got none", i+1, len(c.Steps))
+				}
+				if !step.ExpectError.MatchString(err.Error()) {
+					t.Fatalf("Step %d/%d error running import, expected an error with pattern, no match on: %s", i+1, len(c.Steps), err)
```
Comment (bflad) [inline helper/resource/testing_new.go:114]: Would it be possible to return the `ExpectError` regular expression in the error message for easier troubleshooting?

```suggestion
					t.Fatalf("Step %d/%d error running import, expected an error with pattern (%s), no match on: %s", i+1, len(c.Steps), step.ExpectError.String(), err)
```

Comment (anGie44) [reply helper/resource/testing_new.go:114]: definitely would be helpful 👍 in V1 the error msg used `"Step %d, expected error:\n\n%s\n\nTo match:\n\n%s\n\n",
						i, err, step.ExpectError))` , happy to commit something similar or the one suggested

**Comment by bflad** [comment]
This would also close https://github.com/hashicorp/terraform-plugin-sdk/issues/528 in its current form.
